### ISSUE TITLE
Change entityTracker array to a hashmap?

### ISSUE THREAD

**Issue by drakemj** [Adamek-K/feather-engine#18] opened 2022-10-04 06:14 UTC
Currently, entityTracker is defined in main as an array of entities of size 2056, like this:

![image](https://user-images.githubusercontent.com/62521534/193744428-bca1f958-b71e-4684-9ab6-60f72ed89167.png)

Which is defined as an extern global in rigidentity.h and entity.h. In entity.cpp, new entities are created and the pointers are put into this array. Every time a new entity is created, a global int is incremented for an ID and pushed into the array like so:

![image](https://user-images.githubusercontent.com/62521534/193745385-4b0d133b-94f3-4d49-8597-03a0a0b2dd59.png)

So the obvious problem is that games can easily surpass this entity limit. Additionally, as new entities are destroyed, they will not be removed from the entityTracker, and the draw function in main will iterate through the entire array up to the currentID. This is wasted computation, and I think it could maybe be nice to just replace this with a dynamic hashmap. When an entity is destroyed, it can remove it from the hashmap, and main can simply iterate through the hashmap each frame. This still would allow you to disable Entities temporarily via Disable() and Enable() and keep it in the hashmap.

I've created a prototype that seemingly works that I will try to get into a pull request soon

**Comment by Adamek-K** [comment] 2022-10-04 06:41
Hey, thanks, yeah the static array was intended as more of a placeholder while I figured out something better, a hashmap sounds like a great solution. Thanks!

**Comment by drakemj** [comment] 2022-10-04 07:02
Yeah, I assumed it was a placeholder. Put it in as PR just now (hopefully no problems!)

**Comment by Adamek-K** [comment] 2022-10-04 08:15
Merged #19

**Closed by Adamek-K** 2022-10-04 08:15 UTC
